name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update Versions
      env:
        VERSION_PREFIX: '1.2'
        VERSION_SUFFIX: ${{github.run_number}}
      run: |
        VERSION=$VERSION_PREFIX.$VERSION_SUFFIX
        sed -i bak "s:<Version>1.0.0</Version>:<Version>$VERSION</Version>:g" src/CrossGraphics.csproj
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Restore Workloads
      run: sudo dotnet workload restore
    - name: Restore Packages
      run: dotnet restore
    - name: Test
      run: dotnet test -f net8.0-macos tests/CrossGraphicsTests.csproj
    - name: Build Library
      run: dotnet build -c Release --no-restore src/CrossGraphics.csproj
    - name: Package
      if: github.event_name == 'push'
      run: dotnet pack -c Release --no-build -o ./artifacts src/CrossGraphics.csproj
    - name: Upload Package
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v4
      with:
        name: CrossGraphicsPackages
        path: ./artifacts/*
